name: Build & Deploy

on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/checkout@v2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            su durk
            cd /home
            cd /var/www/sail-test
            git pull origin master
            echo 'Done.'
      
